// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated />

namespace Eco.Mods.TechTree
{
    using System.Collections.Generic;
    using Eco.Core.Items;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Skills;
    using Eco.Gameplay.Systems.TextLinks;
    using Eco.Shared.Localization;
    using Eco.Shared.Serialization;

    [Serialized]
    [LocDisplayName("Baked Roast")]
    [Weight(900)]
    [Tag("BakedFood", 1)]
    [Ecopedia("Food", "Baking", createAsSubPage: true, display: InPageTooltip.DynamicTooltip)]
    public partial class BakedRoastItem : FoodItem
    {
        public override LocString DisplayDescription    => Localizer.DoStr("A trussed roast baked to perfection.");
        
        public override float Calories                  => 1000;
        public override Nutrients Nutrition             => new Nutrients() { Carbs = 4, Fat = 10, Protein = 13, Vitamins = 7};
    }

    [RequiresSkill(typeof(BakingSkill), 2)]
    public partial class BakedRoastRecipe :
        RecipeFamily
    {
        public BakedRoastRecipe()
        {
            var product = new Recipe(
                "BakedRoast",
                Localizer.DoStr("Baked Roast"),
                new IngredientElement[]
                {
                    new IngredientElement(typeof(RawRoastItem), 1, typeof(BakingSkill), typeof(BakingLavishResourcesTalent)),   
                },
                new CraftingElement<BakedRoastItem>(1),
                new CraftingElement<TallowItem>(1f)  
                );

            this.Recipes = new List<Recipe> { product };
            this.LaborInCalories = CreateLaborInCaloriesValue(40, typeof(BakingSkill));
            this.CraftMinutes = CreateCraftTimeValue(typeof(BakedRoastRecipe), 2, typeof(BakingSkill), typeof(BakingFocusedSpeedTalent), typeof(BakingParallelSpeedTalent));
            this.ModsPreInitialize();
            this.Initialize(Localizer.DoStr("Baked Roast"), typeof(BakedRoastRecipe));
            this.ModsPostInitialize();
            CraftingComponent.AddRecipe(typeof(BakeryOvenObject), this);
        }

        /// <summary>Hook for mods to customize RecipeFamily before initialization. You can change recipes, xp, labor, time here.</summary>
        partial void ModsPreInitialize();
        /// <summary>Hook for mods to customize RecipeFamily after initialization, but before registration. You can change skill requirements here.</summary>
        partial void ModsPostInitialize();
    }
}
