// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated />

namespace Eco.Mods.TechTree
{
    using System.Collections.Generic;
    using Eco.Core.Items;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Skills;
    using Eco.Gameplay.Systems.TextLinks;
    using Eco.Shared.Localization;
    using Eco.Shared.Serialization;

    [Serialized]
    [LocDisplayName("Baked Heart Of Palm")]
    [Weight(300)]
    [Tag("BakedVegetable", 1)]
    [Tag("BakedFood", 1)]
    [Ecopedia("Food", "Baking", createAsSubPage: true, display: InPageTooltip.DynamicTooltip)]
    public partial class BakedHeartOfPalmItem : FoodItem
    {
        public override LocString DisplayNamePlural     => Localizer.DoStr("Baked Hearts Of Palm");
        public override LocString DisplayDescription    => Localizer.DoStr("Baked heart of palm that retains more nutrients than more simple methods of cooking.");
        
        public override float Calories                  => 700;
        public override Nutrients Nutrition             => new Nutrients() { Carbs = 12, Fat = 4, Protein = 6, Vitamins = 6};
    }

    [RequiresSkill(typeof(BakingSkill), 1)]
    public partial class BakedHeartOfPalmRecipe :
        RecipeFamily
    {
        public BakedHeartOfPalmRecipe()
        {
            var product = new Recipe(
                "BakedHeartOfPalm",
                Localizer.DoStr("Baked Heart Of Palm"),
                new IngredientElement[]
                {
                    new IngredientElement(typeof(HeartOfPalmItem), 8, typeof(BakingSkill), typeof(BakingLavishResourcesTalent)),   
                },
                new CraftingElement<BakedHeartOfPalmItem>(1)
                );

            this.Recipes = new List<Recipe> { product };
            this.LaborInCalories = CreateLaborInCaloriesValue(40, typeof(BakingSkill));
            this.CraftMinutes = CreateCraftTimeValue(typeof(BakedHeartOfPalmRecipe), 2, typeof(BakingSkill), typeof(BakingFocusedSpeedTalent), typeof(BakingParallelSpeedTalent));
            this.ModsPreInitialize();
            this.Initialize(Localizer.DoStr("Baked Heart Of Palm"), typeof(BakedHeartOfPalmRecipe));
            this.ModsPostInitialize();
            CraftingComponent.AddRecipe(typeof(BakeryOvenObject), this);
        }

        /// <summary>Hook for mods to customize RecipeFamily before initialization. You can change recipes, xp, labor, time here.</summary>
        partial void ModsPreInitialize();
        /// <summary>Hook for mods to customize RecipeFamily after initialization, but before registration. You can change skill requirements here.</summary>
        partial void ModsPostInitialize();
    }
}
