// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated />

namespace Eco.Mods.TechTree
{
    using System.Collections.Generic;
    using Eco.Core.Items;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Skills;
    using Eco.Gameplay.Systems.TextLinks;
    using Eco.Shared.Localization;
    using Eco.Shared.Serialization;

    [Serialized]
    [LocDisplayName("Simmered Meat")]
    [Weight(800)]
    [Ecopedia("Food", "Cooking", createAsSubPage: true, display: InPageTooltip.DynamicTooltip)]
    public partial class SimmeredMeatItem : FoodItem
    {
        public override LocString DisplayNamePlural     => Localizer.DoStr("Simmered Meat");
        public override LocString DisplayDescription    => Localizer.DoStr("Meat cooked in meat juices keeps the meat juicy.");
        
        public override float Calories                  => 900;
        public override Nutrients Nutrition             => new Nutrients() { Carbs = 6, Fat = 13, Protein = 18, Vitamins = 5};
    }

    [RequiresSkill(typeof(CookingSkill), 2)]
    public partial class SimmeredMeatRecipe :
        RecipeFamily
    {
        public SimmeredMeatRecipe()
        {
            var product = new Recipe(
                "SimmeredMeat",
                Localizer.DoStr("Simmered Meat"),
                new IngredientElement[]
                {
                    new IngredientElement(typeof(PreparedMeatItem), 2, typeof(CookingSkill), typeof(CookingLavishResourcesTalent)), 
                    new IngredientElement(typeof(MeatStockItem), 1, typeof(CookingSkill), typeof(CookingLavishResourcesTalent)),   
                },
                new CraftingElement<SimmeredMeatItem>(1)
                );

            this.Recipes = new List<Recipe> { product };
            this.LaborInCalories = CreateLaborInCaloriesValue(40, typeof(CookingSkill));
            this.CraftMinutes = CreateCraftTimeValue(typeof(SimmeredMeatRecipe), 4, typeof(CookingSkill), typeof(CookingFocusedSpeedTalent), typeof(CookingParallelSpeedTalent));
            this.ModsPreInitialize();
            this.Initialize(Localizer.DoStr("Simmered Meat"), typeof(SimmeredMeatRecipe));
            this.ModsPostInitialize();
            CraftingComponent.AddRecipe(typeof(CastIronStoveObject), this);
        }

        /// <summary>Hook for mods to customize RecipeFamily before initialization. You can change recipes, xp, labor, time here.</summary>
        partial void ModsPreInitialize();
        /// <summary>Hook for mods to customize RecipeFamily after initialization, but before registration. You can change skill requirements here.</summary>
        partial void ModsPostInitialize();
    }
}
