// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated />

namespace Eco.Mods.TechTree
{
    using Eco.Core.Items;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Players;
    using Eco.Shared.Localization;
    using Eco.Shared.Serialization;

    [Serialized]
    [LocDisplayName("Tallow")]
    [Weight(20)]
    [Fuel(2000)][Tag("Fuel")]
    [Tag("Fat", 1)]
    [Ecopedia("Food", "Ingredients", createAsSubPage: true, display: InPageTooltip.DynamicTooltip)]
    public partial class TallowItem : FoodItem
    {
        public override LocString DisplayNamePlural     => Localizer.DoStr("Tallow");
        public override LocString DisplayDescription    => Localizer.DoStr("Rendered animal fat useful for more than just cooking.");
        
        public override float Calories                  => 100;
        public override Nutrients Nutrition             => new Nutrients() { Carbs = 0, Fat = 8, Protein = 0, Vitamins = 0};
    }

}
