// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated />

namespace Eco.Mods.TechTree
{
    using System.Collections.Generic;
    using Eco.Core.Items;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Skills;
    using Eco.Gameplay.Systems.TextLinks;
    using Eco.Shared.Localization;
    using Eco.Shared.Serialization;

    [Serialized]
    [LocDisplayName("Vegetable Soup")]
    [Weight(900)]
    [Ecopedia("Food", "Cooking", createAsSubPage: true, display: InPageTooltip.DynamicTooltip)]
    public partial class VegetableSoupItem : FoodItem
    {
        public override LocString DisplayDescription    => Localizer.DoStr("Who knew plants in plant broth could be so tasty?");
        
        public override float Calories                  => 1200;
        public override Nutrients Nutrition             => new Nutrients() { Carbs = 12, Fat = 7, Protein = 4, Vitamins = 19};
    }

    [RequiresSkill(typeof(CookingSkill), 2)]
    public partial class VegetableSoupRecipe :
        RecipeFamily
    {
        public VegetableSoupRecipe()
        {
            var product = new Recipe(
                "VegetableSoup",
                Localizer.DoStr("Vegetable Soup"),
                new IngredientElement[]
                {
                    new IngredientElement(typeof(VegetableStockItem), 1, typeof(CookingSkill), typeof(CookingLavishResourcesTalent)), 
                    new IngredientElement(typeof(VegetableMedleyItem), 1, typeof(CookingSkill), typeof(CookingLavishResourcesTalent)),   
                },
                new CraftingElement<VegetableSoupItem>(1)
                );

            this.Recipes = new List<Recipe> { product };
            this.LaborInCalories = CreateLaborInCaloriesValue(40, typeof(CookingSkill));
            this.CraftMinutes = CreateCraftTimeValue(typeof(VegetableSoupRecipe), 4, typeof(CookingSkill), typeof(CookingFocusedSpeedTalent), typeof(CookingParallelSpeedTalent));
            this.ModsPreInitialize();
            this.Initialize(Localizer.DoStr("Vegetable Soup"), typeof(VegetableSoupRecipe));
            this.ModsPostInitialize();
            CraftingComponent.AddRecipe(typeof(CastIronStoveObject), this);
        }

        /// <summary>Hook for mods to customize RecipeFamily before initialization. You can change recipes, xp, labor, time here.</summary>
        partial void ModsPreInitialize();
        /// <summary>Hook for mods to customize RecipeFamily after initialization, but before registration. You can change skill requirements here.</summary>
        partial void ModsPostInitialize();
    }
}
